language: javascript
before_script:
  - npm install typescript
  - npm install ts-node
  - npm install gulp
jobs:
  include:
    - stage: build
      name: "Build"
      script: gulp build
    - stage: lint
      name: "Lint"
      script: gulp lint
    - stage: test
      name: "Unit Tests"
      script: gulp test
    - stage: coverage
      name: "Unit Test Coverage"
      script: gulp coverage
stages:
  - lint
  - build
  - test
  - coverage
