language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install -g npm
  - npm install -g gulp
script:
  - gulp build
  - gulp lint
  - gulp test
  - gulp coverage
